name: Run Tennis Lineup Scripts

on:
  schedule:
    # Schedule: Run every day at 3:00 AM UTC
    - cron: "0 12 * * 3"
  workflow_dispatch: # Allows manual triggering

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: master

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Specify the desired Python version

    # Step 3: Google credentials
    - name: Decode and save Google credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" | base64 --decode > service-account-key.json

    # Step 3: Run First Script
    - name: Run UpdateGSheet.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account-key.json
      run: python UpdateGSheet.py
