name: Run Tennis Lineup Scripts

on:
  schedule:
    # Schedule: Run every day at 3:00 AM UTC
    - cron: "0 12 * * 3"
  workflow_dispatch: # Allows manual triggering

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: master

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Specify the desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run UpdateGSheet Script
    - name: Run UpdateGSheet.py
      env:
        MY_JSON_SECRET: ${{ secrets.SERVICE_ACCOUNT_KEY }}  # Reference the secret
      run: 
        python UpdateGSheet.py

    # Step 5: Debug environment error
    - name: Debug Environment
      env:
        MY_JSON_SECRET: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        if [ -z "$MY_JSON_SECRET" ]; then
          echo "MY_JSON_SECRET is not set!"
          exit 1
        else
          echo "MY_JSON_SECRET is set!"
        fi
