name: Run Python Tests (Mock -> Real)

on:
  push:
    branches: [master]
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  mock-tests:
    name: Tun Tests (Mock Data)
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest gspread python-dotenv pytest-html

     - name: Run mock scenario: valid
        run: |
          mkdir -p reports
          pytest tests/ --data-source=mock --mock-scenario=valid --html=reports/mock_valid.html

      - name: Upload mock valid report
        uses: actions/upload-artifact@v4
        with:
          name: mock-valid-report
          path: reports/mock_valid.html
          retention-days: 7

      - name: Run mock scenario: missing_gender
        run: |
          pytest tests/ --data-source=mock --mock-scenario=missing_gender --html=reports/mock_missing_gender.html

      - name: Upload mock missing_gender report
        uses: actions/upload-artifact@v4
        with:
          name: mock-missing-gender-report
          path: reports/mock_missing_gender.html
          retention-days: 7

      - name: Run mock scenario: invalid_level
        run: |
          pytest tests/ --data-source=mock --mock-scenario=invalid_level --html=reports/mock_invalid_level.html

      - name: Upload mock invalid_level report
        uses: actions/upload-artifact@v4
        with:
          name: mock-invalid-level-report
          path: reports/mock_invalid_level.html
          retention-days: 7

      - name: Run mock scenario: duplicate_names
        run: |
          pytest tests/ --data-source=mock --mock-scenario=duplicate_names --html=reports/mock_duplicate_names.html

      - name: Upload mock duplicate_names report
        uses: actions/upload-artifact@v4
        with:
          name: mock-duplicate-names-report
          path: reports/mock_duplicate_names.html
          retention-days: 7

  real-tests:
    name: Run Tests (Real Data)
    needs: mock-tests   #Only runs if mock tests succeed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest gspread python-dotenv pytest-html

      - name: Run real tests and generate report
        run: |
          mkdir -p reports
          pytest tests/ --data-source=real --html=reports/real_report.html

      - name: Upload real test report
        uses: actions/upload-artifact@v4
        with:
          name: real-test-report
          path: reports/real_report.html
          retention-days: 7